### ISSUE TITLE
Could not load JDBC driver class (MySQL)

### ISSUE THREAD

**Issue by CarlosMecha** [spring-projects/spring-xd#1653]
This bug is related with [XD-2428](https://jira.spring.io/browse/XD-2428). The MySQL driver is not distributed with Spring XD, but the `spring-xd-module-parent`'s pom is configured to exclude that dependency from the jar created by `spring-boot-maven-plugin`.

I guess that pom is generated using [dependencies.properties](dependencies.properties#L105), and the mysql driver is listed there.

We could add a note in the documentation, or remove that dependency if it's not needed.

Spring XD version: 1.2.0.M1 and 1.1.2.RELEASE

**Comment by trisberg** [comment]
If you use MySQL for the batch job repository then you need to add the driver to `xd/lib` and it should be excluded from the modules you build. So, this means that JDBC drivers need to be added to `xd/lib` and not the modules `lib` directory.

**Comment by CarlosMecha** [comment]
Sorry for the late response.

In my case, I need the MySQL driver for a custom module, not for the batch repository. Is it mandatory to add drivers to the `xd/lib` folder?

Thanks!

**Comment by trisberg** [comment]
You could try putting it in the modules `lib` directory and if you use a connection pool use a different implementation than the Tomcat pool that XD uses or you would most likely get classloading issues. The module parent pom is set up to exclude the mysql dependency though since that is the expected scenario so you would have to work around that.

**Comment by CarlosMecha** [comment]
Ok thanks for the explanation! Closing the ticket.
