### ISSUE TITLE
ResourceManager HA creates problem in Spring XD

### ISSUE THREAD

**Issue by rajitsaha** [spring-projects/spring-xd#1771]
While deploying Spring XD via Ambari, we give 
spring.hadoop.resourceManagerHost=<Active ResourceManager> 

Now when due to HA in ResourceManager, StandBy Resource Manager is Active, 
Spring XD Jobs requiring YARN execution fails as it does not have capability to access New Resource Manager

**Comment by sureshcoder** [comment]
We are also facing same issue. An fix planned for this issue?

**Comment by sabbyanandan** [comment]
Hi @rajitsaha and @sureshcoder: There's a separate Spring XD Ambari repo. This one could be related to spring-projects/spring-xd-ambari#9. 

As an FYI: @jvalkeal [released](https://github.com/spring-projects/spring-xd-ambari/releases/tag/v1.3-2) Ambari plugin for Spring XD 1.3 GA bits. It'd be better to upgrade to the latest improvements and bug-fixes.

I'll close this issue; but, please feel free to add your comments to follow spring-projects/spring-xd-ambari#9 directly.

**Comment by sureshcoder** [comment]
Hi @sabbyanandan I upgraded Springxd 1.3 and Ambari plugin for SpringXD 1.3.

I am still facing the same issue

spring-projects/spring-xd-ambari#9. issue is still open. 

If this issue is only because of Ambari plugin then could you point out Spring-XD document which explains configuring SpringXD for resource Manager HA?

**Comment by dlbm** [comment]
@sureshcoder did you get any hints on the documentation for RM HA? Regards.
