### ISSUE TITLE
Kafka from source to sink produce extra bytes?

### ISSUE THREAD

**Issue by khoanguyen123** [spring-projects/spring-xd#1845]
I use Spring XD 1.2.1 and have the following streams:

1.  "file --dir=/tmp/ch3p-rmna-am002 --mode=lines --pattern=*.SDR | kafka --topic=rm-sdrs --inputType=text/plain"

2. "kafka --topics=rm-sdrs --outputType=text/plain --zkconnect=hw1-vapp033:2181 | file --dir=/tmp/myfile --name=all_sdrs"

Input file test.SDR has:
abc
def

Output file all_sdrs.out has:
��^@^Et^@^Cabc
��^@^Et^@^Cdef

Hexdump the all_sdrs.out:
0000000 bfef efbd bdbf 0500 0074 6103 6362 ef0a
0000010 bdbf bfef 00bd 7405 0300 6564 0a66
000001e

Is this a bug or I mis-configured something?

**Comment by trisberg** [comment]
Have you tried `--outputType=text/plain` on the first stream?

**Comment by artembilan** [comment]
After some debugging I see that issue is really around the String `payload` and value-class-type="[B".
Having that we end up on the code (`ProducerConfiguration`):
````java
return this.conversionService.convert(messagePayload, this.producerMetadata.getValueClassType());
````
which shows me in the debug this one:
```
java.lang.Object -> [B : org.springframework.core.serializer.support.SerializingConverter@25d3cfc8
```
So, according to the `ConversionService` state we are going to **serialize** `String`, but not invoke its `getByte()` method. 

On the another side having `--outputType=text/plain` we end up with the `new String(byte[])`.
Therefore those weird symbols in the beginning of the strings.

To solve your issue I can suggest insert something like this before `Kafka sink`:
```
| transfrom --expression=payload.bytes |
```
and remove `--inputType=text/plain` for the `Kafka sink`.

**Comment by mbogoevici** [comment]
Hi, 

The kafka sink expects a `byte[]` payload by default, so you need to convert the output:

`stream create input --definition "file --dir=/tmp/ch3p-rmna-am002 --mode=lines --pattern=*.SDR --output-type=application/octet-stream | kafka --topic=rm-sdrs"`

Then the second definition will convert the stream as it is.

**Comment by artembilan** [comment]
Also see the fix for the Spring Integration Kafka https://github.com/spring-projects/spring-integration-kafka/pull/85

**Comment by mbogoevici** [comment]
We will pull this in Spring XD via upgrade to Spring Integration Kafka 1.3.

**Comment by khoanguyen123** [comment]
@mbogoevici: setting output-type=application/octet-stream works!
@artembilan: I haven't tried adding the transform --expression=payload.bytes, but I'm sure it will work too.

Thanks

**Comment by mbogoevici** [comment]
Ok, great. In the next release we will make this a little more intuitive.

**Comment by mbogoevici** [comment]
Closing this, as it is addressed in both SI Kafka and Spring XD.
