### ISSUE TITLE
Spring XD, Spring Boot, REST etc...

### ISSUE THREAD

**Issue by prismec** [spring-projects/spring-xd#758]
Hi 

First of all I'd like to apologize for posting this question here, but for me it looks like the Spring XD forum linked on the project page is inactive.

We want to start a fresh project using Spring XD and are wondering where the journey of XD is going to ? We plan to manage a few hundred streams and obviously we can do this using the Spring XD REST interface. Since our streams will be pretty proprietary we'll have to write quite a lot of XD modules and we are just curious if there are recommendations how such a scenario is / should be managed. Are there any plans e.g. deploying such a scenario using Spring Boot (custom modules + streams that are automagically made available by just putting an annotation on it etc...) on the roadmap (or do even already exist). 

Are there any higher level frameworks available / planned that help with the management of XD streams (dependencies between streams, abstraction for patterns like error handling, request / response on a stream, etc...). We are actually planning to build something like "higher level modules" that create a bunch of XD streams and are "interfaced" via input/output topics/queues and may depend on each other and we are curious if there is something like that on the Spring XD / Boot / Pivotal roadmap ?

Thanks in advance!
Peter

**Comment by sabbyanandan** [comment]
@ljrittle, @prismec: This is perhaps out-of-date since we are at Spring XD 1.2.1 as our latest GA release. We hope the concerns reported in the earlier milestone release are now alleviated. If you have any other questions, comments or feedback, please don't hesitate to reach us here or via ```spring-xd``` tag in stackoverflow. 

@kalyanvgopal: Please refer to Rabbit's [error handling](http://docs.spring.io/spring-xd/docs/1.2.1.RELEASE/reference/html/#error-handling-message-delivery-failures) section for more details. Since this may not be related to the original issue, please open a new issue or engage with us in stakoverflow for further collaboration.
